/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_strmapi.c                                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: lakdogan <lakdogan@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/10/12 12:11:54 by lakdogan          #+#    #+#             */
/*   Updated: 2025/02/20 18:32:13 by lakdogan         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "./../inc/libft.h"

/**
 * @brief Applies a function to each character of a string.
 *
 * Allocates a new string where each character is generated by applying
 * the function f to the corresponding character of s. The function f
 * receives both the character and its index.
 *
 * @param s The input string.
 * @param f The function to apply on each character.
 * @return A new string resulting from applying f on each character,
 *         or NULL if allocation fails or if s or f is NULL.
 */
char	*ft_strmapi(char const *s, char (*f)(unsigned int, char))
{
	char			*rslt;
	char			*res_ptr;
	unsigned int	i;

	rslt = malloc(ft_strlen(s) + 1);
	if (!s || !f || !rslt)
		return (NULL);
	res_ptr = rslt;
	i = 0;
	while (*s)
		*res_ptr++ = f(i++, *s++);
	*res_ptr = '\0';
	return (rslt);
}
